name    'mjhas-mailserver'
version '1.0.1'
source 'https://github.com/mjhas/mailserver.git'
author 'mjhas'
license 'Apache License 2.0'
summary 'This Module provides a mailserver with postfix as SMTP-Server and dovecot as IMAP Server with virtual configuration stored in a postgres database'
description 'This Module provides a mailserver with postfix as SMTP-Server and dovecot as IMAP Server with virtual configuration stored in a postgres database'
project_page 'https://github.com/mjhas/mailserver.git'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
dependency 'mjhas-amavis', '1.0.0'
dependency 'mjhas-clamav', '1.0.0'
dependency 'mjhas-dovecot', '1.0.1'
dependency 'mjhas-postfix', '1.0.0'
dependency 'puppetlabs-postgresql', '>=3.0.0'
