name    'mjhas-mailserver'
version '0.0.3'
source 'https://github.com/mjhas/mailserver.git'
author 'mjhas'
license 'Apache License 2.0'
summary ''
description 'This Module provides a mailserver with postfix as SMTP-Server and dovecot as IMAP Server with virtual configuration stored in a postgres database '
project_page 'https://github.com/mjhas/mailserver.git'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
dependency 'mjhas-amavis', '0.0.2'
dependency 'mjhas-clamav', '0.0.1'
dependency 'mjhas-dovecot', '0.0.6'
dependency 'mjhas-postfix', '0.0.5'
dependency 'puppetlabs-postgresql', '2.4.1'
